version: '3.7'

services:
  app:
    #volumes:
     # - static:/static
    #env_file:
     # - .env
    build:
      context: .
    container_name: app
    ports:
      - "7000:7000"
    depends_on: 
      - db
    networks:
      - app-tier
  nginx:
    build:
      context: ./
      dockerfile: ./nginx/Dockerfile
    #volumes:
    #  - static:/static
    container_name: anginx
    ports:
      - "83:80"
    depends_on:
      - app
    networks:
      - app-tier 
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    container_name: db
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1valera1
    networks:
      - app-tier

networks:
  app-tier:
    driver: bridge

  
#     networks:
#       node_net:
#         ipv4_address: 172.28.1.4
# networks:
#   node_net:
#     ipam:
#       driver: default
#       config:
#         - subnet: 172.28.0.0/16
#volumes:
#  static: