version: '3.7'

services:
  app:
    #volumes:
     # - static:/static
    #env_file:
     # - .env
    build:
      context: .
    container_name: app
    ports:
      - "7000:7000"
  nginx:
    build:
      context: ./
      dockerfile: ./nginx/Dockerfile
    #volumes:
    #  - static:/static
    container_name: anginx
    ports:
      - "83:80"
    depends_on:
      - app

#volumes:
#  static: